steps:
      # get repo
      - name: Checkout
        uses: actions/checkout@v3
      # setup node environment on runner
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          # cache: npm
      # install dependencies
      - name: Install
        run: npm ci
      # build
      - name: Build
        run: npm run build